var info = [
{title: "Watch Dogs", publisher: "Ubisoft", release: "May 27, 2014", developer: "Ubisoft Montreal, Ubisoft Reflections, Ubisoft Romania, Ubisoft Quebec, Ubisoft Paris", platforms: ": PS3, PS4, Xbox 360, Xbox One, Wii U, PC", 
review:"IGN – 8.4/10, Metacritic – 80/100, Gamespot – 8/10", rated: "Mature", description: ": Watch Dogs is a near future action adventure game staring hacker Aiden Pierce. It follows his troubles after a job goes wrong and a member of his family is killed; Then years later his sister is kidnapped. He must use all of his skills to uncover the truth about what happened with that job to save his sister." },
{title: "Destiny", publisher: "Activision, Sony Computer Entertainment", release: "September 9, 2014", developer: "Bungie", platforms: "PS3, PS4, Xbox 360, Xbox One", review: "IGN – 7.8/10, Metacritic – 76/100, Gamespot – 6/10",
 rated: "teen", description: "Destiny is one of the most ambitious console games to date. It almost defies classification since it borrows elements from so many other genres. The closest classification is an FPS (First Person Shooter) MMORPG (Massively Multiplayer Online Roleplaying Game). It continues to evolve since it’s first release in September 2014." },
{title: "Mortal Kombat X", publisher: "Warner Bros. Interactive Entertainment", release: "April 15, 2015", developer: "NetherRealm Studios, High Voltage Software", platforms: "PS3, PS4, Xbox 360, Xbox One, PC, iOS, Android",
review: ": IGN – 8.4/10, Metacrititc – 84/100, Gamespot -  8/10", rated: "Mature", description: "This is the 10th iteration of the classic brawler. Spanning decades always bringing something new to the table while maintaining its core roots NetherRealm Studios managed another well received fighting game; that’s more gruesome and gory than ever."},
{title: "Infamous Second Son", publisher: "Sony Computer Entertainment", release: "March 21, 2014", developer: "Sucker Punch Productions", platforms: "PS4", review: ": IGN – 8.7/10, Metacritic – 80/100, Gamespot – 8/10",
 rated: "Teen", description: ": Second Son is the third iteration in the Infamous series. It follows Delson Rowe coming to terms with his newly acquired powers and deciding what to do with them. It is an action adventure exclusive to the PS4."},
{title: "The Last of Us", publisher: "Sony Computer Entertainment", release: " June 14, 2014", developer: "Naughty Dog", platforms: "PS3, PS4", 
review: ": IGN – 10/10, Gamespot – 9.6/10, Metacritic – 95/100", rated: "Mature", description: "The last of us is a gritty post apocalyptic action adventure Playstation exclusive based around Joel who whom has been tasked with escorting Ellie across the country. It is presented in an episodic manner based off of the seasons. It has excellent story telling, visuals, and score; It is generally regarded as a masterpiece."}
];
